---
version: "3.8"
services:
  PET_NAME:
    image: p0t4t0sandwich/pet_discord_bot:latest
    container_name: PET_NAME
    environment:
      - TZ=UTC
      - DISCORD_TOKEN=                      # The token of the Discord bot
      - BOT_CLIENT_ID=                      # Bot's Client ID
      - PET_NAME=                           # Pet name
      - UPLOAD_USERS=                       # Discord user IDs that can upload images, separated by commas
      - MONGODB_URI=                        # MongoDB URI
      - MONGODB_DB=                         # MongoDB database name
    restart: unless-stopped